SignalR.EF/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SignalR.EF.Models
{
    [Table("T_PRODUTO")]
    public class Produto
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Nome obrigatório")]
        [MaxLength(50, ErrorMessage = "Máximo 50 caracters.")]
        [Display(Name = "Nome do produto")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Valor obrigatório")]
        [Display(Name = "Valor do produto")]
        [DataType(DataType.Currency)]
        [Range(0, 9999999999999999.99, ErrorMessage = "Valor inválido")]
        public decimal Valor { get; set; }
    }
}

SignalR.EF/Controllers/ProdutoController.cs
using Microsoft.AspNet.SignalR;
using SignalR.EF.DAL;
using SignalR.EF.Hubs;
using SignalR.EF.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalR.EF.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly BancoContext _ctx;

        public ProdutoController()
        {
            _ctx = new BancoContext();
        }

        #region GETs
        [HttpGet]
        public ActionResult Listar()
        {
            var lista = _ctx.Produtos.ToList();
            return View(lista);
        }

        [HttpGet]
        public ActionResult AtualizarTabela()
        {
            var lista = _ctx.Produtos.ToList();
            return PartialView("_tabelaProdutos", lista);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }
        #endregion

        #region POSTs
        [HttpPost]
        public ActionResult Cadastrar(Produto produto)
        {
            if(ModelState.IsValid)
            {
                _ctx.Produtos.Add(produto);
                _ctx.SaveChanges();                
                Push();
            }
            else
            {
                TempData["msg"] = "Dados incorretos.";
                return View(produto);
            }

            TempData["msg"] = produto.Nome + " cadastrado com sucesso!";
            return RedirectToAction("Cadastrar");
        }
        #endregion

        public void Push()
        {
            var hubCtx = GlobalHost.ConnectionManager.GetHubContext<ProdutoHub>();
            hubCtx.Clients.All.NotificarClientes();            
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _ctx.Dispose();
        }
    }
}

SignalR.EF/Views/Produto/Cadastrar.cshtml
@model SignalR.EF.Models.Produto
@{
    ViewBag.Title = "Cadastrar Produto";
}

<h2>Cadastrar</h2>

@if(TempData["msg"] != null)
{
    <div class="row">
        <div class="col-xs-3">
            <div class="alert alert-info">
                <p>@TempData["msg"].ToString()</p>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                @Html.LabelFor(p=>p.Nome)
                @Html.TextBoxFor(p=>p.Nome, new { @class="form-control" })
                @Html.ValidationMessageFor(p=>p.Nome)
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Valor)
                @Html.TextBoxFor(p => p.Valor, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Valor)
            </div>

            <div class="form-group">
                <input type="submit" name="btnSalvar" value="Salvar" class="btn btn-success" />
            </div>
        }
    </div>
</div>

SignalR.EF/Views/Produto/Listar.cshtml
@model IList<SignalR.EF.Models.Produto>
@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Produtos</h2>
<div class="row">
    <div class="col-xs-12">
        @Html.Partial("_tabelaProdutos", Model)
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="~/signalr/hubs"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            //objeto de proxy do signalr
            var prodHub = $.connection.produtoHubSignalR;                              

            //atualizar tabela com a notificação
            prodHub.client.notificarClientes = function () {
                atualizar();
            }

            //conectar cliente no hub
            $.connection.hub.start();

        });

        function atualizar() {
             $.ajax({
                    url: '@Url.Action("AtualizarTabela")',
                    contentType: 'application/html',
                    type: 'GET',
                    success: function (data) {                        
                        $('#tabelaProdutos').html(data);
                    }
             });
        }
    </script>
}

SignalR.EF/Views/Produto/_tabelaProdutos.cshtml
<table class="table table-hover" id="tabelaProdutos">
    <thead>
        <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Valor</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Nome</td>
                <td>@item.Valor</td>
            </tr>
        }
    </tbody>

</table>

SignalR.EF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SignalR", "Listar", "Produto", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Listar Produtos", "Listar", "Produto", new { }, new { })</li>
                    <li>@Html.ActionLink("Cadastrar Produto", "Cadastrar", "Produto", new { }, new { })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", false)
</body>
</html>